---
services:
  scaffold:
    build:
      context: "."
      dockerfile: Sources/Scaffold.WebApi/Dockerfile
    depends_on:
      - postgres
      - jaeger
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=postgres;Username=postgres;
      JAEGER_SERVICE_NAME: Scaffold
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    image: "${DOCKER_REGISTRY}scaffold"
    ports:
      -
        mode: ingress
        protocol: tcp
        published: 80
        target: 80
      -
        mode: ingress
        protocol: tcp
        published: 8081
        target: 8081
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      -
        source: postgres_pgdata
        target: /var/lib/postgresql/data
        type: volume
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      -
        mode: ingress
        protocol: tcp
        published: 16686
        target: 16686
    volumes:
      -
        source: jaeger_tmp
        target: /tmp
        type: volume
version: "3.5"
volumes:
  postgres_pgdata: ~
  jaeger_tmp: ~
